server:
  port: 8082
  context-path: /ui
  


security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/htm/
    resource:
      userInfoUri: http://localhost:8081/auth/htm/


spring:
  thymeleaf:
    cache: false